# Generated by Django 3.2.8 on 2022-03-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('title', models.CharField(max_length=32, verbose_name='通知标题')),
                ('detail', models.CharField(max_length=125, verbose_name='通知详情')),
                ('creatTime', models.CharField(db_column='create_time', max_length=19, verbose_name='通知时间')),
            ],
            options={
                'db_table': 'notices',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('userName', models.CharField(db_column='user_name', max_length=32, verbose_name='用户账号')),
                ('passWord', models.CharField(max_length=32, verbose_name='用户密码')),
                ('name', models.CharField(max_length=20, verbose_name='用户姓名')),
                ('gender', models.CharField(max_length=4, verbose_name='用户性别')),
                ('age', models.IntegerField(verbose_name='用户年龄')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('email', models.CharField(max_length=32, verbose_name='电子邮箱')),
                ('type', models.CharField(max_length=20, verbose_name='用户身份')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]